# Generated by Django 5.2.4 on 2025-07-15 02:55

from django.db import migrations

def populate_status(apps, schemaeditor):
    entries = {
        "published": "A post visible to all users",
        "draft": "A post only the author can view",
        "archived": "A post visible to logged in users"
    }
    Status = apps.get_model("posts", "Status")
    for key, value in entries.items():
        status_obj = Status(name=key, description=value)
        status_obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(populate_status)
    ]
