# Generated by Django 5.2.4 on 2025-07-19 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20250714_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('subtitle', models.CharField(max_length=256)),
                ('body', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Issue',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='subtitle',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='status',
            name='body',
        ),
        migrations.RemoveField(
            model_name='status',
            name='title',
        ),
        migrations.AddField(
            model_name='status',
            name='name',
            field=models.CharField(default=2, max_length=120),
            preserve_default=False,
        ),
    ]
